/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    NEXT_PUBLIC_VERSION: process.env.NEXT_PUBLIC_VERSION,
    NEXT_PUBLIC_API_TIMEOUT: process.env.NEXT_PUBLIC_API_TIMEOUT,
    NEXT_PUBLIC_KEYCLOAK_URL: process.env.NEXT_PUBLIC_KEYCLOAK_URL,
    NEXT_PUBLIC_KEYCLOAK_REALM: process.env.NEXT_PUBLIC_KEYCLOAK_REALM,
    NEXT_PUBLIC_KEYCLOAK_CLIENT_ID_BASE: process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID_BASE,
    NEXT_PUBLIC_CLOUD_PRODUCTION_BUILD: process.env.NEXT_PUBLIC_CLOUD_PRODUCTION_BUILD,
    NEXT_PUBLIC_ANALYTICS_TRACKING_ID: process.env.NEXT_PUBLIC_ANALYTICS_TRACKING_ID,
    NEXT_PUBLIC_API_BASEURL: process.env.NEXT_PUBLIC_API_BASEURL,
    GENERATE_SOURCEMAP: process.env.GENERATE_SOURCEMAP,
  }
}

module.exports = nextConfig
