export const RaceOrEthicityData = [
  { value: "1", text: "American Indian, Native American, First Nations, or Alaska Native" },
  { value: "2", text: "Asian or Asian American" },
  { value: "3", text: "Black or African American" },
  { value: "4", text: "Hispanic, Latino/a/x, or of Spanish origin" },
  { value: "5", text: "Native Hawaiian or Pacific Islander" },
  { value: "6", text: "White" },
  // { value: "7", text: "Prefer to self-describe" },
  { value: "8", text: "None of these" },
];
export const GenderData = [
  { value: "1", text: "Male" },
  { value: "2", text: "Female" },
  { value: "3", text: "Transgender" },
  { value: "4", text: "Non-binary" },
  { value: "5", text: "Prefer not to say" },
];
export const JobRoleData = [
  { value: "23", text: "Advanced Practice Nurse - CNS, CRNA, NP, etc." },
  { value: "24", text: "Ancillary Services - Nutrition, Rehab, Social Work, Chaplain, etc." },
  { value: "12", text: "Dental Technician" },
  { value: "11", text: "Dentist" },
  { value: "1", text: "Doctor" },
  { value: "15", text: "Housekeeping Services" },
  { value: "3", text: "Medical Scribe" },
  { value: "2", text: "Medical Student" },
  { value: "14", text: "Mental Health Professional" },
  { value: "5", text: "Nurse" },
  { value: "6", text: "Nursing Assistant" },
  { value: "4", text: "Nursing Student" },
  { value: "22", text: "Other" },
  { value: "17", text: "Other Administrative Support" },
  { value: "16", text: "Patient-facing Administrative Support (e.g., front desk)", },
  { value: "9", text: "Pharmacist" },
  { value: "10", text: "Pharmacy Technician" },
  { value: "8", text: "Physician Assistant" },
  { value: "18", text: "Researcher" },
  { value: "7", text: "Technician" },
];